-- CREATE TABLE 
CREATE TABLE CITIES (
	NAME VARCHAR(50),
	COUNTRY VARCHAR(50),
	POPULATION INTEGER,
	AREA INTEGER
);

-- INSERT DATA INTO CITIES TABLE 
INSERT INTO CITIES (NAME,COUNTRY,POPULATION,AREA)
			VALUES ('TOKYO','JAPAN',30000000,8223),
					('DHELI','INDIA',28000000,7800),
					('SHANGHAI','CHINA',27045600,7500),
					('DHAKA','BANGLADESH',25000000,6500);
					
-- SHOW DATA FROM CITIES TABLE 					
SELECT COUNT (*) FROM CITIES;

-- MATHMETIAL OPERATION ON CITIES TABLE
SELECT NAME, POPULATION / AREA AS DENSITY 
FROM CITIES;

-- STRING OPERATION ON CITIES TABLE 
SELECT NAME || COUNTRY FROM CITIES;

SELECT NAME ||','|| COUNTRY FROM CITIES;

SELECT NAME ||','|| COUNTRY AS LOCATION FROM CITIES;

SELECT CONCAT(NAME,COUNTRY) AS LOCATION FROM CITIES;

SELECT CONCAT(NAME,', ',COUNTRY) AS LOCATION FROM CITIES;

SELECT CONCAT(LOWER(NAME),', ',LOWER(COUNTRY)) AS LOCATION FROM CITIES;

SELECT LOWER(CONCAT(NAME,', ',COUNTRY)) AS LOCATION FROM CITIES;


-- FILTERING 
SELECT NAME,AREA FROM CITIES WHERE AREA > 7800;

SELECT NAME, AREA FROM CITIES WHERE AREA < 7800;

SELECT NAME, AREA FROM CITIES WHERE AREA >= 7800;

SELECT NAME, AREA FROM CITIES WHERE AREA <= 7800;

--COMPOUND OPERATIOR 
SELECT NAME, AREA FROM CITIES WHERE AREA != 7800;

SELECT NAME, AREA FROM CITIES WHERE AREA BETWEEN 7500 AND 8500;

SELECT NAME, AREA FROM CITIES WHERE NAME IN ('TOKYO','DHAKA');

SELECT NAME, AREA FROM CITIES WHERE NAME NOT IN ('TOKYO','DHAKA');

SELECT NAME, AREA FROM CITIES WHERE NAME NOT IN ('TOKYO','DHAKA') AND AREA = 7500;

SELECT NAME, AREA FROM CITIES WHERE NAME NOT IN ('TOKYO','DHAKA') OR AREA =7500;

-- calculation 

SELECT NAME, POPULATION / AREA AS "POPULATION DENSITY"
FROM CITIES
WHERE POPULATION / AREA > 3607;

-- UPDATE 
UPDATE CITIES 
SET POPULATION = 29000000
WHERE NAME = 'TOKYO';

SELECT * FROM CITIES;

-- DELETE 
DELETE FROM CITIES 
WHERE NAME = 'TOKYO';

SELECT * FROM CITIES;

DELETE FROM CITIES 
WHERE NAME NOT IN ('TOKYO');

