

COPY DBSIZE FROM 'C:\Users\rakib.islam\OneDrive - ABG Technologies Limited\Desktop\csv\pktcbdbp.txt' DELIMITER ',' CSV HEADER;

TRUNCATE TABLE DBSIZE;

SELECT * FROM DBSIZE;

DROP TABLE DBSIZE;


SELECT DBNAME,SIZE,BACKUP_DATE FROM DBSIZE ORDER BY BACKUP_DATE DESC;

SELECT DBNAME,SIZE,BACKUP_DATE FROM DBSIZE ORDER BY BACKUP_DATE ASC;

SELECT DBNAME,SIZE,BACKUP_DATE FROM DBSIZE
WHERE BACKUP_DATE BETWEEN '2023-12-01' AND '2023-12-31'
ORDER BY BACKUP_DATE ASC;

select size from dbsize;

drop table pocketdb;

Create table pocketdb (size varchar(50),backup_date date,dbname varchar(50));

COPY pocketdb FROM 'C:\Users\rakib.islam\OneDrive - ABG Technologies Limited\Desktop\csv\pktwdbp.txt' DELIMITER ',' CSV HEADER;

select * from pocketdb;


SELECT DBNAME,SIZE BACKUP_DATE FROM POCKETDB
WHERE BACKUP_DATE BETWEEN '2023-12-01' AND '2023-12-31'
AND DBNAME ='pktcbdbp'
ORDER BY BACKUP_DATE ASC;

SELECT DISTINCT BACKUP_DATE,DBNAME,SIZE FROM POCKETDB
WHERE BACKUP_DATE BETWEEN '2023-12-01' AND '2023-12-31'
AND DBNAME ='pktcbdbp'
ORDER BY BACKUP_DATE ASC;

SELECT DISTINCT ON (BACKUP_DATE) BACKUP_DATE, DBNAME, SIZE,TRIM ( ' K' FROM SIZE) AS SIZE_KB, TRIM ( ' M' FROM SIZE) AS SIZE_MB, TRIM (' G' FROM SIZE ) AS SIZE_GB FROM POCKETDB
WHERE BACKUP_DATE BETWEEN '2023-09-01' AND '2023-09-30'
AND DBNAME ='pktcbdbp'
ORDER BY BACKUP_DATE ASC;

select * from pocketdb; 

SELECT DISTINCT DBNAME FROM POCKETDB;


